# Generated by Django 3.1.6 on 2021-03-15 21:30

from django.db import migrations
from rest_framework.authtoken.models import Token

class Migration(migrations.Migration):

    dependencies = [
        ('some', '0001_initial'),
    ]

    operations = [
    ]
