# Generated by Django 3.1.5 on 2021-03-13 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0004_auto_20210312_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_time_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 7, 8, 16, 894579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 7, 8, 16, 894579, tzinfo=utc)),
        ),
    ]
