# Generated by Django 3.1.7 on 2021-03-25 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('some', '0005_auto_20210324_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('last_action', models.DateTimeField(default=datetime.datetime(2021, 3, 25, 17, 58, 44, 961023, tzinfo=utc))),
            ],
            bases=('authtoken.token',),
        ),
    ]
