# Generated by Django 3.1.7 on 2021-03-25 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0006_temporarytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 21, 49, 49, 2634, tzinfo=utc)),
        ),
    ]
