# Generated by Django 3.1.7 on 2021-03-25 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0007_auto_20210325_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytoken',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 21, 52, 59, 613502)),
        ),
    ]
