# Generated by Django 3.1.5 on 2021-03-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0008_auto_20210313_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='busy',
        ),
        migrations.AddField(
            model_name='show',
            name='busy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
