# Generated by Django 3.1.7 on 2021-03-29 13:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('some', '0009_auto_20210326_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='some.show'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporarytoken',
            name='last_action',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 13, 22, 15, 670678, tzinfo=utc)),
        ),
    ]
