# Generated by Django 3.1.5 on 2021-03-12 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_myuser_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_time',
        ),
        migrations.AddField(
            model_name='show',
            name='show_time_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 16, 4, 23, 905610)),
        ),
        migrations.AddField(
            model_name='show',
            name='show_time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 16, 4, 23, 905587)),
        ),
    ]
