# Generated by Django 3.1.5 on 2021-03-12 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210312_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='busy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 16, 45, 25, 703609)),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 16, 45, 25, 703570)),
        ),
    ]
