# Generated by Django 3.1.5 on 2021-03-13 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210313_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_time_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 7, 8, 39, 577508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='show',
            name='show_time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 7, 8, 39, 577508, tzinfo=utc)),
        ),
    ]
