# Generated by Django 3.1.5 on 2021-03-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='busy',
        ),
        migrations.AddField(
            model_name='show',
            name='free',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
